"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup


APP = ['main.py']
APP_NAME = 'Website Template Builder'
DATA_FILES = ['src']
OPTIONS = {}

setup(
    name=APP_NAME,
    version=2.0,
    author='Filip Bongcam',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
